### ISSUE TITLE
TextField error with version 0.1.16

### ISSUE THREAD

**Issue by newapx** [rigor789/nativescript-vue#61]
In my template
`<text-field v-model="name"></text-field>`

On start app i got error
```
System.err: Calling js method onCreate failed
System.err: Error: textfield has no property text. (TypeError: html.replace is not a function)
System.err: File: "file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js, line: 2268, column: 6
System.err: StackTrace:
System.err:     Frame: function:'setAttribute', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2268, column: 13
System.err:     Frame: function:'updateAttrs', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4608, column: 11
System.err:     Frame: function:'invokeCreateHooks', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4203, column: 20
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4095, column: 11
System.err:     Frame: function:'createChildren', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4187, column: 9
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4093, column: 9
System.err:     Frame: function:'patch', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4517, column: 7
System.err:     Frame: function:'Vue._update', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3715, column: 19
System.err:     Frame: function:'updateComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3838, column: 10
System.err:     Frame: function:'get', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2947, column: 27
System.err:     Frame: function:'Watcher', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2930, column: 14
System.err:     Frame: function:'mountComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3842, column: 17
System.err:     Frame: function:'mount', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9422, column: 5
System.err:     Frame: function:'Vue$3.$mount', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9448, column: 16
System.err:     Frame: function:'init', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 7900, column: 13
System.err:     Frame: function:'createComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4117, column: 9
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4060, column: 9
System.err:     Frame: function:'createChildren', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4187, column: 9
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4093, column: 9
System.err:     Frame: function:'createChildren', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4187, column: 9
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4093, column: 9
System.err:     Frame: function:'createChildren', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4187, column: 9
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4093, column: 9
System.err:     Frame: function:'patch', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4517, column: 7
System.err:     Frame: function:'Vue._update', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3715, column: 19
System.err:     Frame: function:'updateComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3838, column: 10
System.err:     Frame: function:'get', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2947, column: 27
System.err:     Frame: function:'Watcher', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2930, column: 14
System.err:     Frame: function:'mountComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3842, column: 17
System.err:     Frame: function:'mount', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9422, column: 5
System.err:     Frame: function:'Vue$3.$mount', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9448, column: 16
System.err:     Frame: function:'init', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 7900, column: 13
System.err:     Frame: function:'createComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4117, column: 9
System.err:     Frame: function:'createElm', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4060, column: 9
System.err:     Frame: function:'patch', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 4553, column: 9
System.err:     Frame: function:'Vue._update', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3715, column: 19
System.err:     Frame: function:'updateComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3838, column: 10
System.err:     Frame: function:'get', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2947, column: 27
System.err:     Frame: function:'Watcher', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2930, column: 14
System.err:     Frame: function:'mountComponent', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3842, column: 17
System.err:     Frame: function:'create', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9410, column: 9
System.err:     Frame: function:'', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 72, column: 22
System.err:     Frame: function:'', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 123, column: 16
System.err:     Frame: function:'FrameBase.navigate', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 191, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 589, column: 19
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/test.vue.routersample/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:5231)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
System.err:     ... 11 more
```
I comment in `nativescript-vue` in function ` setAttribute`
lines
```
 } else if (key === 'text') {
        this.nativeView[key] = he_1(value);
```
and the error left

**Comment by rigor789** [comment]
This is odd, I just tested the same exact code, and it seems to be working fine, can you show a bit more of the code, so I can give it a test?

```
this.nativeView[key] = he_1(value);
```
This basically converts html entities to actual characters to make things like `&copy;` work.

**Comment by newapx** [comment]
I have component TestComponent in .vue file
```
<template>
    <stack-layout>
        <label class="large">Test Component</label>

        <label>{{ $data }}</label>

        <text-field v-model="name"></text-field>
        <text-field v-model="age"></text-field>
        <text-field v-model="occupation"></text-field>
    </stack-layout>
</template>

<script>
    export default {

        data() {
            return {
                name: 'John',
                age: 34,
                occupation: 'Developer'
            }
        }
    }
</script>
```
and on first page in app template
```
<page>
    <scroll-view>
        <stack-layout>
            <grid-layout rows="auto" columns="*,*">
                <stack-layout col="0" orientation="horizontal">
                    <label>Count: {{ count }}</label>
                    <button @tap="count--">-1</button>
                </stack-layout>
                <button col="1" @tap="gotoPage1()">PAGE 1</button>
            </grid-layout>
            <test-component style="margin-top: 40;"></test-component>
            <label> sample text </label>
            <test-component style="margin-top: 10;"></test-component>
        </stack-layout>
    </scroll-view>
</page>
```
