### ISSUE TITLE
sample app-with-tabview-router.js crash

### ISSUE THREAD

**Issue by Alphmega** [rigor789/nativescript-vue#90]
```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.vuesample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/org.nativescript.vuesample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16
System.err: StackTrace:
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.vuesample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.vuesample/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2519)
System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:161)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5541)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/org.nativescript.vuesample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16
System.err: StackTrace:
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.vuesample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.vuesample/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:6287)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
System.err:     ... 9 more
```

**Comment by rigor789** [comment]
I have never finished that sample, so it is normal that it crashes. I will have to organize these samples a lot better in the near future to avoid any confusion.
